services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: study_async
    restart: always
    volumes:
      - .:/app
      - static-data:/staticfiles # Diretório de arquivos estáticos dentro do container Nginx
      - media-data:/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - database

  database:
    image: postgres:15
    container_name: study_async_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER} 
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  static-data: {}
  media-data: {}
  pgdata: {}

