# Generated by Django 5.0.1 on 2024-01-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flashcardchallenge",
            name="got_it_right",
            field=models.BooleanField(),
        ),
    ]
