# Generated by Django 5.0.1 on 2024-01-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0002_alter_flashcardchallenge_got_it_right"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flashcardchallenge",
            name="got_it_right",
            field=models.BooleanField(default=False),
        ),
    ]
