# Generated by Django 5.0.1 on 2024-02-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_viewbook"),
        ("flashcards", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="tags",
        ),
        migrations.AddField(
            model_name="book",
            name="tags",
            field=models.ManyToManyField(to="flashcards.category"),
        ),
    ]
