# Generated by Django 5.0.1 on 2024-02-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_remove_book_tags_book_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="book",
            name="tags",
            field=models.ManyToManyField(to="books.tag"),
        ),
    ]
